

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Slider;
            }
        }
    }
}

namespace ImageProcessing
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ ctlImg;
        private: ::Windows::UI::Xaml::Controls::Slider^ slider1;
        private: ::Windows::UI::Xaml::Controls::Slider^ slider2;
        private: ::Windows::UI::Xaml::Controls::Slider^ slider3;
    };
}

